<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one or more
  contributor license agreements.  See the NOTICE file distributed with
  this work for additional information regarding copyright ownership.
  The ASF licenses this file to You under the Apache License, Version 2.0
  (the "License"); you may not use this file except in compliance with
  the License.  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.apache.ranger</groupId>
    <artifactId>ranger-pinot-plugin-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Ranger Plugin for Apache Pinot</name>
    <description>Apache Ranger authorization plugin for Apache Pinot</description>
    <url>https://github.com/apache/ranger-plugin-pinot</url>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <modules>
        <module>ranger-pinot-plugin</module>
        <module>ranger-pinot-plugin-shim</module>
        <module>ranger-pinot-plugin-distro</module>
        <module>ranger-pinot-plugin-it</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>17</maven.compiler.release>

        <ranger.version>2.8.0</ranger.version>
        <pinot.version>1.4.0</pinot.version>

        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <checkstyle.plugin.version>3.1.0</checkstyle.plugin.version>
        <checkstyle.version>8.29</checkstyle.version>
        <checkstyle.failOnViolation>true</checkstyle.failOnViolation>
        <checkstyle.skip>false</checkstyle.skip>
        <rat.plugin.version>0.16.1</rat.plugin.version>
        <spotbugs.plugin.version>4.7.3.5</spotbugs.plugin.version>
        <spotbugs.failOnViolation>false</spotbugs.failOnViolation>

        <maven-surefire-plugin.version>3.2.5</maven-surefire-plugin.version>
        <junit.jupiter.version>5.10.2</junit.jupiter.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.apache.ranger</groupId>
                <artifactId>ranger-plugins-common</artifactId>
                <version>${ranger.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ranger</groupId>
                <artifactId>ranger-plugin-classloader</artifactId>
                <version>${ranger.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ranger</groupId>
                <artifactId>ranger-audit-core</artifactId>
                <version>${ranger.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ranger</groupId>
                <artifactId>ranger-plugins-cred</artifactId>
                <version>${ranger.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.ranger</groupId>
                <artifactId>ranger-intg</artifactId>
                <version>${ranger.version}</version>
            </dependency>

            <dependency>
                <groupId>org.apache.pinot</groupId>
                <artifactId>pinot-spi</artifactId>
                <version>${pinot.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.pinot</groupId>
                <artifactId>pinot-broker</artifactId>
                <version>${pinot.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.pinot</groupId>
                <artifactId>pinot-controller</artifactId>
                <version>${pinot.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.pinot</groupId>
                <artifactId>pinot-core</artifactId>
                <version>${pinot.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>${junit.jupiter.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>${checkstyle.plugin.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>com.puppycrawl.tools</groupId>
                        <artifactId>checkstyle</artifactId>
                        <version>${checkstyle.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>checkstyle-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <consoleOutput>true</consoleOutput>
                            <includeTestSourceDirectory>true</includeTestSourceDirectory>
                            <configLocation>${maven.multiModuleProjectDirectory}/dev-support/checkstyle.xml</configLocation>
                            <suppressionsLocation>${maven.multiModuleProjectDirectory}/dev-support/checkstyle-suppressions.xml</suppressionsLocation>
                            <skip>${checkstyle.skip}</skip>
                            <failOnViolation>${checkstyle.failOnViolation}</failOnViolation>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.rat</groupId>
                <artifactId>apache-rat-plugin</artifactId>
                <version>${rat.plugin.version}</version>
                <executions>
                    <execution>
                        <id>rat-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <excludeSubProjects>false</excludeSubProjects>
                    <consoleOutput>true</consoleOutput>
                    <excludes>
                        <exclude>dev-support/**</exclude>
                        <exclude>**/target/**</exclude>
                        <exclude>.git/**</exclude>
                        <exclude>.gitignore</exclude>
                        <exclude>**/*.iml</exclude>
                        <exclude>.idea/**</exclude>
                        <exclude>**/src/main/resources/**/*.json</exclude>
                        <exclude>ranger-pinot-plugin-it/docker/**</exclude>
                        <exclude>**/docker/**</exclude>
                        <exclude>**/src/test/resources/**/*.json</exclude>
                        <exclude>**/src/test/resources/**/*.csv</exclude>
                        <exclude>.planning/**</exclude>
                        <exclude>.pi/**</exclude>
                        <exclude>NOTICE</exclude>
                        <exclude>LICENSE</exclude>
                        <exclude>config.json</exclude>
                        <exclude>**/.classpath</exclude>
                        <exclude>**/.project</exclude>
                        <exclude>**/.factorypath</exclude>
                        <exclude>**/.settings/**</exclude>
                    </excludes>
                </configuration>
            </plugin>

            <plugin>
                <groupId>com.github.spotbugs</groupId>
                <artifactId>spotbugs-maven-plugin</artifactId>
                <version>${spotbugs.plugin.version}</version>
                <executions>
                    <execution>
                        <id>spotbugs-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                        <configuration>
                            <failOnError>${spotbugs.failOnViolation}</failOnError>
                            <includeFilterFile>${maven.multiModuleProjectDirectory}/dev-support/spotbugsIncludeFile.xml</includeFilterFile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
